name: Build & Export IPA

on:
  push:
    branches:
      - ios-15
  workflow_dispatch:
    inputs:
      branch:
        description: "Escolha o branch pra buildar manualmente"
        required: false
        default: "ios-15"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Resolve Swift Packages
        run: swift package resolve

      - name: Build BitChat (unsigned)
        run: |
          xcodebuild \
            -project bitchat.xcodeproj \
            -scheme "bitchat (iOS)" \
            -sdk iphoneos \
            -configuration Release \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            clean build

      - name: Create .ipa
        run: |
          mkdir -p build_artifacts
          APP_PATH=$(find . -type d -name "*.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "❌ Nenhum .app encontrado!"
            exit 1
          fi
          echo "✅ .app encontrado em $APP_PATH"
          pushd "$(dirname "$APP_PATH")"
          zip -r ../bitchat.ipa "$(basename "$APP_PATH")"
          popd
          mv bitchat.ipa build_artifacts/

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitchat-unsigned
          path: build_artifacts/bitchat.ipa
